apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "educates"
spec:
  title: "Git fundamentals"
  description: "Learn the fundamentals of Git"
  url: https://github.com/GlobeTeam-Platform/ga-kursus-git
  tags:
    - git
  publish:
    image: "$(image_repository)/workshop-files:$(workshop_version)"
  workshop:
    files:
    - image:
        url: $(image_repository)/workshop-files:$(workshop_version)
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    namespaces:
      budget: medium
    applications:
      slides:
        enabled: true
      git:
        enabled: true
      terminal:
        enabled: true
        #layout: split
      editor:
        enabled: true
      console:
        enabled: false
      docker:
        enabled: false
      registry:
        enabled: false
      vcluster:
        enabled: false
